id: I4B1750BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T15:37:55+00:00'
last_modified: '2022-06-08T17:01:20.921470+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5624
  title: གསུང་འབུམ། རོང་ཟོམ་ཆོས་བཟང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B32D:
      image_group_id: I3CN5626
      title: ''
      total_pages: 445
      order: 1
      base_file: B32D.txt
    14A8:
      image_group_id: I3CN5627
      title: ''
      total_pages: 373
      order: 2
      base_file: 14A8.txt
    C27A:
      image_group_id: I3CN5628
      title: ''
      total_pages: 439
      order: 3
      base_file: C27A.txt
    '4327':
      image_group_id: I3CN5629
      title: ''
      total_pages: 423
      order: 4
      base_file: 4327.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
